name: CI

on:
  push:
    branches: [main, dev, qa, prod]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Display project files (test step)
        run: ls -la

